export const LoadData = [
  {
    id: 1,
    age: 25,
    pickupDate: new Date("2024-09-01").toLocaleDateString(),
    trip: {
      pickup: "New York",
      dropoff: "Chicago",
    },
    dh: 10,
    rate: 4.1,
    equipment: "Reefer",
    size: "53ft",
    companyName: "TransCorp",
    status: "Active",
  },
  {
    id: 2,
    age: 34,
    pickupDate: new Date("2024-09-02").toLocaleDateString(),
    trip: {
      pickup: "Los Angeles",
      dropoff: "San Francisco",
    },
    dh: 20,
    rate: 4.3,
    equipment: "Van",
    size: "48ft",
    companyName: "FreightLine",
    status: "Inactive",
  },
  {
    id: 3,
    age: 28,
    pickupDate: new Date("2024-09-03").toLocaleDateString(),
    trip: {
      pickup: "Dallas",
      dropoff: "Houston",
    },
    dh: 15,
    rate: 4.2,
    equipment: "Flatbed",
    size: "53ft",
    companyName: "TruckNation",
    status: "Active",
  },
  {
    id: 4,
    age: 41,
    pickupDate: new Date("2024-09-04").toLocaleDateString(),
    trip: {
      pickup: "Miami",
      dropoff: "Orlando",
    },
    dh: 8,
    rate: 3.8,
    equipment: "Van",
    size: "53ft",
    companyName: "LogiMove",
    status: "Inactive",
  },
  {
    id: 5,
    age: 30,
    pickupDate: new Date("2024-09-05").toLocaleDateString(),
    trip: {
      pickup: "Atlanta",
      dropoff: "Nashville",
    },
    dh: 5,
    rate: 3.7,
    equipment: "Reefer",
    size: "53ft",
    companyName: "PrimeTrans",
    status: "Active",
  },
  {
    id: 6,
    age: 32,
    pickupDate: new Date("2024-09-06").toLocaleDateString(),
    trip: {
      pickup: "Seattle",
      dropoff: "Portland",
    },
    dh: 18,
    rate: 3.9,
    equipment: "Flatbed",
    size: "48ft",
    companyName: "QuickHaul",
    status: "Inactive",
  },
  {
    id: 7,
    age: 36,
    pickupDate: new Date("2024-09-07").toLocaleDateString(),
    trip: {
      pickup: "Phoenix",
      dropoff: "Las Vegas",
    },
    dh: 12,
    rate: 4.7,
    equipment: "Van",
    size: "53ft",
    companyName: "SwiftLogistics",
    status: "Active",
  },
  {
    id: 8,
    age: 29,
    pickupDate: new Date("2024-09-08").toLocaleDateString(),
    trip: {
      pickup: "Denver",
      dropoff: "Salt Lake City",
    },
    dh: 9,
    rate: 4.6,
    equipment: "Reefer",
    size: "53ft",
    companyName: "EagleFreight",
    status: "Active",
  },
  {
    id: 9,
    age: 38,
    pickupDate: new Date("2024-09-09").toLocaleDateString(),
    trip: {
      pickup: "Chicago",
      dropoff: "Detroit",
    },
    dh: 14,
    rate: 4.4,
    equipment: "Flatbed",
    size: "48ft",
    companyName: "StarTrucks",
    status: "Inactive",
  },
  {
    id: 10,
    age: 27,
    pickupDate: new Date("2024-09-10").toLocaleDateString(),
    trip: {
      pickup: "Philadelphia",
      dropoff: "Boston",
    },
    dh: 11,
    rate: 2.4,
    equipment: "Van",
    size: "53ft",
    companyName: "LoadMaster",
    status: "Active",
  },
  {
    id: 11,
    age: 35,
    pickupDate: new Date("2024-09-11").toLocaleDateString(),
    trip: {
      pickup: "Austin",
      dropoff: "San Antonio",
    },
    dh: 7,
    rate: 3.2,
    equipment: "Reefer",
    size: "53ft",
    companyName: "RapidTrans",
    status: "Active",
  },
  {
    id: 12,
    age: 40,
    pickupDate: new Date("2024-09-12").toLocaleDateString(),
    trip: {
      pickup: "Kansas City",
      dropoff: "Omaha",
    },
    dh: 10,
    rate: 3.8,
    equipment: "Flatbed",
    size: "53ft",
    companyName: "LogiPro",
    status: "Inactive",
  },
  {
    id: 13,
    age: 26,
    pickupDate: new Date("2024-09-13").toLocaleDateString(),
    trip: {
      pickup: "Indianapolis",
      dropoff: "Louisville",
    },
    dh: 6,
    rate: 3.9,
    equipment: "Van",
    size: "48ft",
    companyName: "TransportX",
    status: "Active",
  },
  {
    id: 14,
    age: 31,
    pickupDate: new Date("2024-09-14").toLocaleDateString(),
    trip: {
      pickup: "San Diego",
      dropoff: "Phoenix",
    },
    dh: 20,
    rate: 4.0,
    equipment: "Reefer",
    size: "53ft",
    companyName: "HaulPro",
    status: "Active",
  },
  {
    id: 15,
    age: 33,
    pickupDate: new Date("2024-09-15").toLocaleDateString(),
    trip: {
      pickup: "Salt Lake City",
      dropoff: "Reno",
    },
    dh: 13,
    rate: 4.1,
    equipment: "Flatbed",
    size: "48ft",
    companyName: "ExpressFreight",
    status: "Inactive",
  },
  {
    id: 16,
    age: 37,
    pickupDate: new Date("2024-09-16").toLocaleDateString(),
    trip: {
      pickup: "Columbus",
      dropoff: "Cleveland",
    },
    dh: 9,
    rate: 2.3,
    equipment: "Van",
    size: "53ft",
    companyName: "RoadWarrior",
    status: "Active",
  },
  {
    id: 17,
    age: 42,
    pickupDate: new Date("2024-09-17").toLocaleDateString(),
    trip: {
      pickup: "Minneapolis",
      dropoff: "Milwaukee",
    },
    dh: 16,
    rate: 3.5,
    equipment: "Reefer",
    size: "53ft",
    companyName: "DriveMax",
    status: "Inactive",
  },
  {
    id: 18,
    age: 28,
    pickupDate: new Date("2024-09-18").toLocaleDateString(),
    trip: {
      pickup: "Memphis",
      dropoff: "Little Rock",
    },
    dh: 19,
    rate: 5,
    equipment: "Flatbed",
    size: "48ft",
    companyName: "FreightX",
    status: "Active",
  },
  {
    id: 19,
    age: 39,
    pickupDate: new Date("2024-09-19").toLocaleDateString(),
    trip: {
      pickup: "Oklahoma City",
      dropoff: "Tulsa",
    },
    dh: 8,
    rate: 4.8,
    equipment: "Van",
    size: "53ft",
    companyName: "FreightForce",
    status: "Inactive",
  },
  {
    id: 20,
    age: 43,
    pickupDate: new Date("2024-09-20").toLocaleDateString(),
    trip: {
      pickup: "Las Vegas",
      dropoff: "Los Angeles",
    },
    dh: 17,
    rate: 1.0,
    equipment: "Reefer",
    size: "53ft",
    companyName: "FastFreight",
    status: "Active",
  },
];
