export const LoadData = [
  {
    id: 1,
    age: "20 Min ago",
    pickupDate: "20 June, 2024",
    trip: {
      pickup: "New York",
      dropoff: "Chicago",
    },
    dh: 254,
    trailer: 254,
    rate: 4.1,
    size: "53ft, 40,000ibs",
    companyName: "Tiron Shipment",
    status: "active",
  },
  {
    id: 1,
    age: "20 Min ago",
    pickupDate: "20 June, 2024",
    trip: {
      pickup: "New York",
      dropoff: "Chicago",
    },
    dh: 254,
    trailer: 254,
    rate: 4.1,
    size: "53ft, 40,000ibs",
    companyName: "Tiron Shipment",
    status: "inactive",
  },
  {
    id: 1,
    age: "20 Min ago",
    pickupDate: "20 June, 2024",
    trip: {
      pickup: "New York",
      dropoff: "Chicago",
    },
    dh: 254,
    trailer: 254,
    rate: 4.1,
    size: "53ft, 40,000ibs",
    companyName: "Tiron Shipment",
    status: "active",
  },
];
