export const timezoneList = [
  { country: "United States", timezone: "GMT-5 (America/New_York)" },
  { country: "United States", timezone: "GMT-8 (America/Los_Angeles)" },
  { country: "Canada", timezone: "GMT-5 (America/Toronto)" },
  { country: "Canada", timezone: "GMT-8 (America/Vancouver)" },
  { country: "United Kingdom", timezone: "GMT+0 (Europe/London)" },
  { country: "Germany", timezone: "GMT+1 (Europe/Berlin)" },
  { country: "France", timezone: "GMT+1 (Europe/Paris)" },
  { country: "India", timezone: "GMT+5:30 (Asia/Kolkata)" },
  { country: "China", timezone: "GMT+8 (Asia/Shanghai)" },
  { country: "Japan", timezone: "GMT+9 (Asia/Tokyo)" },
  { country: "Australia", timezone: "GMT+10 (Australia/Sydney)" },
  { country: "Brazil", timezone: "GMT-3 (America/Sao_Paulo)" },
  { country: "Russia", timezone: "GMT+3 (Europe/Moscow)" },
  { country: "South Africa", timezone: "GMT+2 (Africa/Johannesburg)" },
  { country: "Mexico", timezone: "GMT-6 (America/Mexico_City)" },
  { country: "Argentina", timezone: "GMT-3 (America/Argentina/Buenos_Aires)" },
  { country: "Saudi Arabia", timezone: "GMT+3 (Asia/Riyadh)" },
  { country: "United Arab Emirates", timezone: "GMT+4 (Asia/Dubai)" },
  { country: "Nigeria", timezone: "GMT+1 (Africa/Lagos)" },
  { country: "South Korea", timezone: "GMT+9 (Asia/Seoul)" },
  { country: "New Zealand", timezone: "GMT+12 (Pacific/Auckland)" },
  { country: "Turkey", timezone: "GMT+3 (Europe/Istanbul)" },
  { country: "Spain", timezone: "GMT+1 (Europe/Madrid)" },
  { country: "Italy", timezone: "GMT+1 (Europe/Rome)" },
  { country: "Sweden", timezone: "GMT+1 (Europe/Stockholm)" },
  { country: "Netherlands", timezone: "GMT+1 (Europe/Amsterdam)" },
  { country: "Egypt", timezone: "GMT+2 (Africa/Cairo)" },
  { country: "Israel", timezone: "GMT+2 (Asia/Jerusalem)" },
  { country: "Indonesia", timezone: "GMT+7 (Asia/Jakarta)" },
  { country: "Vietnam", timezone: "GMT+7 (Asia/Ho_Chi_Minh)" },
  { country: "Philippines", timezone: "GMT+8 (Asia/Manila)" },
  { country: "Thailand", timezone: "GMT+7 (Asia/Bangkok)" },
  { country: "Malaysia", timezone: "GMT+8 (Asia/Kuala_Lumpur)" },
  { country: "Singapore", timezone: "GMT+8 (Asia/Singapore)" },
  { country: "Pakistan", timezone: "GMT+5 (Asia/Karachi)" },
  { country: "Bangladesh", timezone: "GMT+6 (Asia/Dhaka)" },
  { country: "Sri Lanka", timezone: "GMT+5:30 (Asia/Colombo)" },
  { country: "Kenya", timezone: "GMT+3 (Africa/Nairobi)" },
  { country: "Ethiopia", timezone: "GMT+3 (Africa/Addis_Ababa)" },
  { country: "Ghana", timezone: "GMT+0 (Africa/Accra)" },
  { country: "Chile", timezone: "GMT-4 (America/Santiago)" },
  { country: "Peru", timezone: "GMT-5 (America/Lima)" },
  { country: "Colombia", timezone: "GMT-5 (America/Bogota)" },
  { country: "Venezuela", timezone: "GMT-4 (America/Caracas)" },
  { country: "Cuba", timezone: "GMT-5 (America/Havana)" },
  { country: "Honduras", timezone: "GMT-6 (America/Tegucigalpa)" },
  { country: "Jamaica", timezone: "GMT-5 (America/Jamaica)" },
  { country: "Iceland", timezone: "GMT+0 (Atlantic/Reykjavik)" },
  { country: "Norway", timezone: "GMT+1 (Europe/Oslo)" },
  { country: "Finland", timezone: "GMT+2 (Europe/Helsinki)" },
  { country: "Denmark", timezone: "GMT+1 (Europe/Copenhagen)" },
  { country: "Poland", timezone: "GMT+1 (Europe/Warsaw)" },
  { country: "Czech Republic", timezone: "GMT+1 (Europe/Prague)" },
  { country: "Austria", timezone: "GMT+1 (Europe/Vienna)" },
  { country: "Belgium", timezone: "GMT+1 (Europe/Brussels)" },
  { country: "Portugal", timezone: "GMT+0 (Europe/Lisbon)" },
  { country: "Ireland", timezone: "GMT+0 (Europe/Dublin)" },
  { country: "Switzerland", timezone: "GMT+1 (Europe/Zurich)" },
  { country: "Romania", timezone: "GMT+2 (Europe/Bucharest)" },
  { country: "Bulgaria", timezone: "GMT+2 (Europe/Sofia)" },
  { country: "Greece", timezone: "GMT+2 (Europe/Athens)" },
  { country: "Hungary", timezone: "GMT+1 (Europe/Budapest)" },
  { country: "Croatia", timezone: "GMT+1 (Europe/Zagreb)" },
  { country: "Slovakia", timezone: "GMT+1 (Europe/Bratislava)" },
  { country: "Ukraine", timezone: "GMT+2 (Europe/Kiev)" },
  { country: "Georgia", timezone: "GMT+4 (Asia/Tbilisi)" },
  { country: "Armenia", timezone: "GMT+4 (Asia/Yerevan)" },
  { country: "Azerbaijan", timezone: "GMT+4 (Asia/Baku)" },
  { country: "Kazakhstan", timezone: "GMT+6 (Asia/Almaty)" },
  { country: "Uzbekistan", timezone: "GMT+5 (Asia/Tashkent)" },
  { country: "Afghanistan", timezone: "GMT+4:30 (Asia/Kabul)" },
  { country: "Maldives", timezone: "GMT+5 (Indian/Maldives)" },
  { country: "Nepal", timezone: "GMT+5:45 (Asia/Kathmandu)" },
  { country: "Fiji", timezone: "GMT+12 (Pacific/Fiji)" },
  { country: "Papua New Guinea", timezone: "GMT+10 (Pacific/Port_Moresby)" },
  { country: "Samoa", timezone: "GMT+13 (Pacific/Apia)" },
  { country: "Tonga", timezone: "GMT+13 (Pacific/Tongatapu)" }
];
